export interface Dish {
  id?: number;
  name?: string;
  subtitle?: string;
  image?: string;
  mainImage?: string;
  number?: number;
  rating?: number;
  chef?: string;
  chefTitle?: string;
  description?: string;
  longDescription?: string;
  price?: number;
}

export type CategoryType =
  | "food"
  | "entrees"
  | "cocktails"
  | "drinks"
  | "brunch";

export const categories: Record<string, Dish[]> = {
  food: [
    {
      id: 4,
      name: "Mussels",
      subtitle: "Atlantic Fresh",
      image: "/images/Mussels.png",
      mainImage: "/images/Mussels.png",
      number: 4,
      rating: 4.7,
      chef: "Chef Pierre",
      chefTitle: "Seafood Master",
      description:
        "Atlantic mussels / fire roasted tomato and smoked paprika sauce / sourdough / garlic and juniper oil",
      price: 24,
    },
    {
      id: 5,
      name: "Cauliflower",
      subtitle: "Tempura Style",
      image: "/images/Cauliflower.png",
      mainImage: "/images/Cauliflower.png",
      number: 5,
      rating: 4.4,
      chef: "Chef Yuki",
      chefTitle: "Fusion Specialist",
      description:
        "Tempura fried / porcini powdered / tajin / romesco / garlic aioli",
      price: 18,
    },
    {
      id: 6,
      name: "Croquettes",
      subtitle: "Sweet & Savory",
      image: "/images/Croquettes.png",
      mainImage: "/images/Croquettes.png",
      number: 6,
      rating: 4.5,
      chef: "Chef Sophie",
      chefTitle: "Pastry & Apps",
      description:
        "Sweet potato / carrot / potato / brown sugar / wildberry compote / lavender",
      price: 17,
    },
    {
      id: 7,
      name: "Elk Carpaccio",
      subtitle: "Wild Game",
      image: "/images/ElkCarpaccio.png",
      mainImage: "/images/ElkCarpaccio.png",
      number: 7,
      rating: 4.9,
      chef: "Chef Marcus",
      chefTitle: "Game Meat Expert",
      description:
        "Sliced elk / smoked miso aioli drizzle / pickled blueberries / shallots / shaved parmesan / crostini",
      price: 21,
    },
    {
      id: 11,
      name: "Bruschetta",
      subtitle: "Forest Mushroom",
      image: "/images/Bruschetta.png",
      mainImage: "/images/Bruschetta.png",
      number: 11,
      rating: 4.5,
      chef: "Chef Luca",
      chefTitle: "Italian Specialist",
      description:
        "Foraged mushroom medley / crostini / fromage blanc / balsamic glaze",
      price: 18,
    },
    {
      id: 12,
      name: "Beef Tenderloin",
      subtitle: "Ash Crusted",
      image: "/images/BeefTenderloin.png",
      mainImage: "/images/BeefTenderloin.png",
      number: 1,
      rating: 4.9,
      chef: "Chef Laurent",
      chefTitle: "Master Butcher",
      description:
        "6oz ash crusted beef tenderloin / wild mushroom and truffle puree / glazed heirloom carrots / thyme and black garlic jus",
      price: 59,
    },
    {
      id: 13,
      name: "Chicken",
      subtitle: "Roasted Perfection",
      image: "/images/Chicken.png",
      mainImage: "/images/Chicken.png",
      number: 2,
      rating: 4.6,
      chef: "Chef Sarah",
      chefTitle: "Poultry Specialist",
      description:
        "Roasted chicken breast / creamy chestnut and foraged mushroom risotto / thyme jus / pomme gastrique",
      price: 37,
    },
    {
      id: 16,
      name: "Tagliatelle",
      subtitle: "Short Rib Pasta",
      image: "/images/demo.png",
      mainImage: "/images/demo.png",
      number: 5,
      rating: 4.8,
      chef: "Chef Giovanni",
      chefTitle: "Pasta Maestro",
      description:
        "Slow braised short rib / tagliatelle pasta / roasted mushrooms / confit baby tomatoes / dill cream sauce",
      price: 36,
    },
    {
      id: 17,
      name: "Pescatore",
      subtitle: "Seafood Linguine",
      image: "/images/Pescatore.png",
      mainImage: "/images/Pescatore.png",
      number: 6,
      rating: 4.7,
      chef: "Chef Marco",
      chefTitle: "Italian Seafood",
      description:
        "Linguine / mussels / jumbo shrimp / baby scallops / capers / lemon / cream sauce or spicy tomato sauce",
      price: 36,
    },
    {
      id: 20,
      name: "Wildfire Molcajete",
      subtitle: "Tableside Experience",
      image: "/images/WildfireMolcajete.png",
      mainImage: "/images/WildfireMolcajete.png",
      number: 9,
      rating: 5.0,
      chef: "Chef Diego",
      chefTitle: "Fire & Stone Master",
      description:
        "Beef striploin / lobster tail / chicken / mussels / shrimp / scallops / roasted tomatillo broth / smoked herb / stone bowl / ignited liqueur / serves two guests",
      price: 95,
    },
    // {
    //   id: 21,
    //   name: "Additional - Add Chicken",
    //   subtitle: "Entree Add-on",
    //   image: "placeholder",
    //   mainImage: "placeholder",
    //   number: 10,
    //   rating: 0,
    //   chef: "Kitchen Staff",
    //   chefTitle: "Helper",
    //   description: "Add a portion of chicken to your entree.",
    //   price: 10,
    // },
    // {
    //   id: 22,
    //   name: "Additional - Add Lobster Tail",
    //   subtitle: "Entree Add-on",
    //   image: "placeholder",
    //   mainImage: "placeholder",
    //   number: 11,
    //   rating: 0,
    //   chef: "Kitchen Staff",
    //   chefTitle: "Helper",
    //   description: "Add a lobster tail to your entree.",
    //   price: 24,
    // },
    // {
    //   id: 23,
    //   name: "Additional - Gluten Free Pasta",
    //   subtitle: "Entree Add-on",
    //   image: "placeholder",
    //   mainImage: "placeholder",
    //   number: 12,
    //   rating: 0,
    //   chef: "Kitchen Staff",
    //   chefTitle: "Helper",
    //   description: "Substitute for gluten free pasta.",
    //   price: 5,
    // },
    // {
    //   id: 24,
    //   name: "Additional - Add Salmon",
    //   subtitle: "Entree Add-on",
    //   image: "placeholder",
    //   mainImage: "placeholder",
    //   number: 13,
    //   rating: 0,
    //   chef: "Kitchen Staff",
    //   chefTitle: "Helper",
    //   description: "Add a portion of salmon to your entree.",
    //   price: 13,
    // },
    // {
    //   id: 25,
    //   name: "Additional - Add Shrimps (3)",
    //   subtitle: "Entree Add-on",
    //   image: "placeholder",
    //   mainImage: "placeholder",
    //   number: 14,
    //   rating: 0,
    //   chef: "Kitchen Staff",
    //   chefTitle: "Helper",
    //   description: "Add 3 shrimps to your entree.",
    //   price: 9,
    // },
    // {
    //   id: 26,
    //   name: "Additional - Gluten Free Bread",
    //   subtitle: "Entree Add-on",
    //   image: "placeholder",
    //   mainImage: "placeholder",
    //   number: 15,
    //   rating: 0,
    //   chef: "Kitchen Staff",
    //   chefTitle: "Helper",
    //   description: "Substitute for gluten free bread.",
    //   price: 4,
    // },
  ],
  drinks: [
    {
      id: 27,
      name: "Golden Smoke",
      subtitle: "Cocktail",
      image: "/cocktailDrinks/goldenSmoke-removebg-preview.png",
      mainImage: "/cocktailDrinks/goldenSmoke-removebg-preview.png",
      description:
        "a warm whisper of bourbon and honey drifts through rosemary mist — where sweetness meets the forest fire's last glow.",
    },
    {
      id: 28,
      name: "Wild Grove",
      subtitle: "Cocktail",
      image: "/cocktailDrinks/wildGroove-removebg-preview.png",
      mainImage: "/cocktailDrinks/wildGroove-removebg-preview.png",
      description:
        "a burst of blackcurrant and basil, bright and alive — like stepping barefoot through a secret garden after rain",
    },
    {
      id: 29,
      name: "Whispering Spruce",
      subtitle: "Cocktail",
      image: "/cocktailDrinks/whisperingSpruce-removebg-preview.png",
      mainImage: "/cocktailDrinks/whisperingSpruce-removebg-preview.png",
      description:
        "cool gin and birch sweetness breathe the soul of the alpine woods — dark,resinous, and quietly eternal.",
    },
    {
      id: 30,
      name: "Echo of the Forest",
      subtitle: "Cocktail",
      image: "/cocktailDrinks/echoOfTheForest.jpg",
      mainImage: "/cocktailDrinks/echoOfTheForest.jpg",
      description:
        "herbal and mysterious — where pine and honeyed spice weave the secrets only the trees remember.",
    },
    {
      id: 31,
      name: "Forest Ember Old Fashioned",
      subtitle: "Cocktail",
      image: "/cocktailDrinks/forestEmberedOldFashioned-removebg-preview.png",
      mainImage:
        "/cocktailDrinks/forestEmberedOldFashioned-removebg-preview.png",
      description:
        "smoky spruce and bourbon warmth glow like dying embers beneath autumn leaves.",
    },
    {
      id: 32,
      name: "Enchanted Bloom",
      subtitle: "Cocktail",
      image: "/cocktailDrinks/enchantedBloom-removebg-preview.png",
      mainImage: "/cocktailDrinks/enchantedBloom-removebg-preview.png",
      description:
        "delicate violet and citrus light shimmer like moonlight over hidden petals.",
    },
    {
      id: 33,
      name: "Dash of Dasha",
      subtitle: "Cocktail",
      image: "/cocktailDrinks/dasOfDasha-removebg-preview.png",
      mainImage: "/cocktailDrinks/dasOfDasha-removebg-preview.png",
      description:
        "dark roast and fire collide — a storm of energy, passion, and lingering heat.",
    },
    {
      id: 34,
      name: "Orchard Stroll",
      subtitle: "Cocktail",
      image: "/cocktailDrinks/orchardStroll-removebg-preview.png",
      mainImage: "/cocktailDrinks/orchardStroll-removebg-preview.png",
      description:
        "golden apples, warm spice, and apricot sunlight — the taste of autumn captured in one slow breath.",
    },
    {
      id: 35,
      name: "Molech's Mule",
      subtitle: "Cocktail",
      image: "/cocktailDrinks/molechsMule-removebg-preview.png",
      mainImage: "/cocktailDrinks/molechsMule-removebg-preview.png",
      description:
        "bright lime and crisp cucumber rise through ginger fire — a refreshing spark born from earth and flame.",
    },
  ],
  cocktails: [],
  // drinks: [
  //   {
  //     id: 35,
  //     name: "House Lager",
  //     subtitle: "Draught Beer",
  //     image:
  //       "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400&h=300&fit=crop",
  //     mainImage:
  //       "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&h=600&fit=crop",
  //     number: 9,
  //     rating: 4.4,
  //     chef: "Brewmaster Tom",
  //     chefTitle: "Beer Expert",
  //     description: "Crisp and refreshing house lager on tap.",
  //     price: 9.75,
  //   },
  //   {
  //     id: 36,
  //     name: "Seachange 'The Wolf' Hazy Pale Ale",
  //     subtitle: "Draught Beer",
  //     image:
  //       "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400&h=300&fit=crop",
  //     mainImage:
  //       "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&h=600&fit=crop",
  //     number: 10,
  //     rating: 4.6,
  //     chef: "Brewmaster Jake",
  //     chefTitle: "Craft Beer Specialist",
  //     description: "Hazy pale ale on tap.",
  //     price: 11,
  //   },
  //   {
  //     id: 37,
  //     name: "Seachange Irish Red",
  //     subtitle: "Draught Beer",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 11,
  //     rating: 4.6,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "Irish Red on tap.",
  //     price: 11,
  //   },
  //   {
  //     id: 38,
  //     name: "Odd Company Good Chemistry IPA",
  //     subtitle: "Draught Beer",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 12,
  //     rating: 4.6,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "IPA on tap.",
  //     price: 12,
  //   },
  //   {
  //     id: 39,
  //     name: "Sapporo",
  //     subtitle: "Bottled Beer",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 13,
  //     rating: 4.4,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "Bottled beer.",
  //     price: 9,
  //   },
  //   {
  //     id: 40,
  //     name: "88 Brewing Vietnamese Coffee Stout",
  //     subtitle: "Canned Beer",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 14,
  //     rating: 4.7,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "Stout in a can.",
  //     price: 11,
  //   },
  //   {
  //     id: 41,
  //     name: "Troubled Monk Open Road Brown Ale",
  //     subtitle: "Canned Beer",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 15,
  //     rating: 4.5,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "Brown Ale in a can.",
  //     price: 9,
  //   },
  //   {
  //     id: 42,
  //     name: "Odd Company Mandarin Sour",
  //     subtitle: "Canned Beer",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 16,
  //     rating: 4.7,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "Sour in a can.",
  //     price: 9,
  //   },
  //   {
  //     id: 44,
  //     name: "Alley Kat Pumpkin Spiced Ale",
  //     subtitle: "Canned Beer",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 18,
  //     rating: 4.5,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "Seasonal spiced ale in a can.",
  //     price: 8,
  //   },
  //   {
  //     id: 45,
  //     name: "Seachange Death Wave Light Lager",
  //     subtitle: "Canned Beer",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 19,
  //     rating: 4.4,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "Light lager in a can.",
  //     price: 9,
  //   },
  //   {
  //     id: 46,
  //     name: "Cider",
  //     subtitle: "Canned Cider",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 20,
  //     rating: 4.3,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "Cider in a can.",
  //     price: 9,
  //   },
  //   {
  //     id: 47,
  //     name: "Big Rock Non-Alcoholic Golden Ale",
  //     subtitle: "Non-Alcoholic Beer",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 21,
  //     rating: 4.0,
  //     chef: "Brewmaster",
  //     chefTitle: "Specialist",
  //     description: "Non-alcoholic Golden Ale.",
  //     price: 9,
  //   },
  // ],

  // wines: [
  //   // Rosé & Bubbles
  //   {
  //     id: 49,
  //     name: "Ken Forrester 'Petit' Rosé",
  //     subtitle: "South Africa",
  //     image:
  //       "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop",
  //     mainImage:
  //       "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=600&fit=crop",
  //     number: 1,
  //     rating: 4.5,
  //     chef: "Sommelier Jean",
  //     chefTitle: "Wine Expert",
  //     description: "Rosé from South Africa. 6oz $12 | 9oz $16 | Bottle $42",
  //     price: 12,
  //   },
  //   {
  //     id: 50,
  //     name: "Gerard Bertrand Cote de Roses Rosé",
  //     subtitle: "France",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 2,
  //     rating: 4.6,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Rosé from France.",
  //     price: 65,
  //   },
  //   {
  //     id: 51,
  //     name: "Lamarca Prosecco",
  //     subtitle: "Italy",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 3,
  //     rating: 4.7,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Prosecco from Italy. 6oz $12 | Bottle $48",
  //     price: 12,
  //   },
  //   {
  //     id: 52,
  //     name: "J.L Denois Sparkling Brut",
  //     subtitle: "France",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 4,
  //     rating: 4.8,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Sparkling Brut from France.",
  //     price: 72,
  //   },
  //   {
  //     id: 53,
  //     name: "Domaine Carneros Brut",
  //     subtitle: "California",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 5,
  //     rating: 4.9,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Brut from California.",
  //     price: 105,
  //   },

  //   // White Wines
  //   {
  //     id: 54,
  //     name: "Perlage Pinot Grigio",
  //     subtitle: "Italy",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 6,
  //     rating: 4.5,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Pinot Grigio from Italy. 6oz $13 | 9oz $18 | Bottle $52",
  //     price: 13,
  //   },
  //   {
  //     id: 55,
  //     name: "Ken Forrester Sauvignon Blanc",
  //     subtitle: "South Africa",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 7,
  //     rating: 4.6,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description:
  //       "Sauvignon Blanc from South Africa. 6oz $12 | 9oz $16 | Bottle $42",
  //     price: 12,
  //   },
  //   {
  //     id: 56,
  //     name: "Family Tree 'The Goat Lady' Chardonnay",
  //     subtitle: "Canada",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 8,
  //     rating: 4.7,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Chardonnay from Canada. 6oz $13 | 9oz $18 | Bottle $52",
  //     price: 13,
  //   },
  //   {
  //     id: 57,
  //     name: "Gehringer Riesling",
  //     subtitle: "Canada",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 9,
  //     rating: 4.8,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Riesling from Canada. 6oz $13 | 9oz $18 | Bottle $52",
  //     price: 13,
  //   },
  //   {
  //     id: 58,
  //     name: "Pierre Sparr Gewürztraminer",
  //     subtitle: "France",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 10,
  //     rating: 4.5,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Gewürztraminer from France. Bottle $52",
  //     price: 52,
  //   },
  //   {
  //     id: 59,
  //     name: "Honey Bee Chenin Blanc",
  //     subtitle: "South Africa",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 11,
  //     rating: 4.6,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Chenin Blanc from South Africa. Bottle $48",
  //     price: 48,
  //   },
  //   {
  //     id: 60,
  //     name: "Duckhorn Sauvignon Blanc",
  //     subtitle: "California",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 12,
  //     rating: 4.9,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Sauvignon Blanc from California. Bottle $74",
  //     price: 74,
  //   },
  //   {
  //     id: 61,
  //     name: "Henry of Pelham Pinot Grigio",
  //     subtitle: "Canada",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 13,
  //     rating: 4.5,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Pinot Grigio from Canada. Bottle $59",
  //     price: 59,
  //   },
  //   {
  //     id: 62,
  //     name: "Tantalus Old Vines Riesling",
  //     subtitle: "Canada",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 14,
  //     rating: 4.9,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Old Vines Riesling from Canada. Bottle $76",
  //     price: 76,
  //   },
  //   {
  //     id: 63,
  //     name: "Chablis",
  //     subtitle: "France",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 15,
  //     rating: 4.8,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Chablis from France. Bottle $95",
  //     price: 95,
  //   },
  //   {
  //     id: 64,
  //     name: "Joseph Drouhin Cote de Beaune Chardonnay",
  //     subtitle: "France",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 16,
  //     rating: 5.0,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Chardonnay from France. Bottle $240",
  //     price: 240,
  //   },

  //   // Red Wines
  //   {
  //     id: 65,
  //     name: "Yalumba Cabernet Sauvignon '21",
  //     subtitle: "Australia",
  //     image:
  //       "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=300&fit=crop",
  //     mainImage:
  //       "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&h=600&fit=crop",
  //     number: 17,
  //     rating: 4.7,
  //     chef: "Sommelier",
  //     chefTitle: "Red Wine Expert",
  //     description:
  //       "Cabernet Sauvignon from Australia. 6oz $14 | 9oz $19 | Bottle $54",
  //     price: 14,
  //   },
  //   {
  //     id: 66,
  //     name: "Luigi Bosca La Linda Malbec '21",
  //     subtitle: "Argentina",
  //     image:
  //       "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=300&fit=crop",
  //     mainImage:
  //       "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&h=600&fit=crop",
  //     number: 18,
  //     rating: 4.8,
  //     chef: "Sommelier",
  //     chefTitle: "Malbec Specialist",
  //     description: "Malbec from Argentina. 6oz $13 | 9oz $18 | Bottle $57",
  //     price: 13,
  //   },
  //   {
  //     id: 67,
  //     name: "Opawa Pinot Noir",
  //     subtitle: "New Zealand",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 19,
  //     rating: 4.8,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description:
  //       "Pinot Noir from New Zealand. 6oz $15 | 9oz $20 | Bottle $59",
  //     price: 15,
  //   },
  //   {
  //     id: 68,
  //     name: "Porta 6 Red Blend",
  //     subtitle: "Portugal",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 20,
  //     rating: 4.6,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Red Blend from Portugal. 6oz $13 | 9oz $18 | Bottle $52",
  //     price: 13,
  //   },
  //   {
  //     id: 69,
  //     name: "Bordeaux",
  //     subtitle: "France",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 21,
  //     rating: 4.7,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Bordeaux from France. 6oz $14 | 9oz $19 | Bottle $54",
  //     price: 14,
  //   },
  //   {
  //     id: 70,
  //     name: "Guardian Peak Merlot",
  //     subtitle: "Canada",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 22,
  //     rating: 4.5,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Merlot from Canada. Bottle $95",
  //     price: 95,
  //   },
  //   {
  //     id: 71,
  //     name: "Frind 'The Premier' Bordeaux Blend",
  //     subtitle: "Canada",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 23,
  //     rating: 4.8,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Bordeaux Blend from Canada. Bottle $129",
  //     price: 129,
  //   },
  //   {
  //     id: 72,
  //     name: "Hugo Shiraz",
  //     subtitle: "Australia",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 24,
  //     rating: 4.7,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Shiraz from Australia. Bottle $95",
  //     price: 95,
  //   },
  //   {
  //     id: 73,
  //     name: "Louis Jadot Beaujolais-Villages",
  //     subtitle: "France",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 25,
  //     rating: 4.6,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Beaujolais-Villages from France. Bottle $52",
  //     price: 52,
  //   },
  //   {
  //     id: 74,
  //     name: "Mission Hill Cabernet Franc",
  //     subtitle: "Canada",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 26,
  //     rating: 4.7,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Cabernet Franc from Canada. Bottle $78",
  //     price: 78,
  //   },
  //   {
  //     id: 75,
  //     name: "Il Bruciato Super Tuscan",
  //     subtitle: "Italy",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 27,
  //     rating: 4.9,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Super Tuscan from Italy. Bottle $89",
  //     price: 89,
  //   },
  //   {
  //     id: 76,
  //     name: "Sueno de Megala",
  //     subtitle: "Spain",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 28,
  //     rating: 4.8,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Wine from Spain. Bottle $95",
  //     price: 95,
  //   },
  //   {
  //     id: 77,
  //     name: "Tantalus Vineyards Pinot Noir",
  //     subtitle: "Canada",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 29,
  //     rating: 4.9,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Pinot Noir from Canada. Bottle $139",
  //     price: 139,
  //   },
  //   {
  //     id: 78,
  //     name: "Volpaia Chianti Classico",
  //     subtitle: "Italy",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 30,
  //     rating: 4.7,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Chianti Classico from Italy. Bottle $74",
  //     price: 74,
  //   },
  //   {
  //     id: 79,
  //     name: "Buehler Zinfandel",
  //     subtitle: "California",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 31,
  //     rating: 4.6,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Zinfandel from California. Bottle $86",
  //     price: 86,
  //   },
  //   {
  //     id: 80,
  //     name: "Roberto Voerzio Barbera d'Alba",
  //     subtitle: "Italy",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 32,
  //     rating: 4.8,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Barbera d'Alba from Italy. Bottle $95",
  //     price: 95,
  //   },
  //   {
  //     id: 81,
  //     name: "Halos de Jupiter Grenache",
  //     subtitle: "France",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 33,
  //     rating: 4.7,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Grenache from France. Bottle $68",
  //     price: 68,
  //   },
  //   {
  //     id: 82,
  //     name: "Chateau Mauvesin Barton",
  //     subtitle: "France",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 34,
  //     rating: 4.9,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Wine from France. Bottle $145",
  //     price: 145,
  //   },
  //   {
  //     id: 83,
  //     name: "Henschke Henry's Seven",
  //     subtitle: "Australia",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 35,
  //     rating: 4.8,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Wine from Australia. Bottle $129",
  //     price: 129,
  //   },
  //   {
  //     id: 84,
  //     name: "Le Ragose Amarone Della Valpolicella '16",
  //     subtitle: "Italy",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 36,
  //     rating: 4.9,
  //     chef: "Sommelier",
  //     chefTitle: "Wine Expert",
  //     description: "Amarone Della Valpolicella from Italy. Bottle $165",
  //     price: 165,
  //   },
  //   {
  //     id: 85,
  //     name: "Paradigm Cabernet Sauvignon '18",
  //     subtitle: "California",
  //     image:
  //       "https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=400&h=300&fit=crop",
  //     mainImage:
  //       "https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=800&h=600&fit=crop",
  //     number: 37,
  //     rating: 5.0,
  //     chef: "Sommelier",
  //     chefTitle: "Premium Wine Specialist",
  //     description: "Cabernet Sauvignon from California. Bottle $295",
  //     price: 295,
  //   },
  //   {
  //     id: 86,
  //     name: "Catena Zapata Agrentino Malbec",
  //     subtitle: "Argentina",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 38,
  //     rating: 5.0,
  //     chef: "Sommelier",
  //     chefTitle: "Premium Wine Specialist",
  //     description: "Malbec from Argentina. Bottle $335",
  //     price: 335,
  //   },
  // ],
  // brunch: [
  //   {
  //     id: 60,
  //     name: "Classic Breakfast",
  //     subtitle: "",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 1,
  //     rating: 4.6,
  //     chef: "Chef Anna",
  //     chefTitle: "Breakfast Lead",
  //     description:
  //       "Two eggs any style / bacon or sausage / hash browns / toast / seasonal fruit",
  //     price: 18,
  //   },
  //   {
  //     id: 61,
  //     name: "Avocado Toast",
  //     subtitle: "",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 2,
  //     rating: 4.8,
  //     chef: "Chef Anna",
  //     chefTitle: "Breakfast Lead",
  //     description:
  //       "Sourdough / smashed avocado / pickled onions / feta / microgreens / chili flakes / lemon oil",
  //     price: 16,
  //   },
  //   {
  //     id: 62,
  //     name: "Eggs Benedict",
  //     subtitle: "",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 3,
  //     rating: 4.9,
  //     chef: "Chef Anna",
  //     chefTitle: "Breakfast Lead",
  //     description:
  //       "Two poached eggs / English muffin / back bacon / hollandaise / hash browns",
  //     price: 19,
  //   },
  //   {
  //     id: 63,
  //     name: "Stuffed French Toast",
  //     subtitle: "",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 4,
  //     rating: 4.8,
  //     chef: "Chef Anna",
  //     chefTitle: "Breakfast Lead",
  //     description:
  //       "House-made brioche / cream cheese filling / berry compote / maple syrup",
  //     price: 17,
  //   },
  //   {
  //     id: 64,
  //     name: "Steak and Eggs",
  //     subtitle: "",
  //     image: "placeholder",
  //     mainImage: "placeholder",
  //     number: 5,
  //     rating: 4.9,
  //     chef: "Chef Anna",
  //     chefTitle: "Breakfast Lead",
  //     description:
  //       "6oz striploin / two eggs any style / hash browns / toast / grilled tomato",
  //     price: 27,
  //   },
  // ],
};
